export type EditRisk = "low" | "moderate" | "destructive" | "external";

export interface EditActionDefinition {
  action: string;
  category: string;
  description: string;
  risk: EditRisk;
  destructive: boolean;
  verification: string;
  adapter: "media-composer-extension";
}

type Seed = [action: string, description: string, risk?: EditRisk, verification?: string];

const CATEGORY_SEEDS: Record<string, Seed[]> = {
  project: [
    ["project.create", "Create a Media Composer project", "moderate"],
    ["project.open", "Open an existing project", "moderate"],
    ["project.save", "Save the current project", "moderate"],
    ["project.saveAs", "Save the project under a new name or path", "moderate"],
    ["project.close", "Close the current project", "moderate"],
    ["project.setFormat", "Change the project raster, rate, or color space", "destructive"],
    ["project.setFilmSettings", "Change film and matchback settings", "moderate"],
    ["project.setWorkingSettings", "Change project-level working settings", "moderate"],
    ["project.refresh", "Refresh project and shared-bin state", "low"],
  ],
  bin: [
    ["bin.create", "Create a bin", "low"],
    ["bin.open", "Open a bin", "low"],
    ["bin.close", "Close a bin", "low"],
    ["bin.save", "Save a bin", "moderate"],
    ["bin.rename", "Rename a bin", "moderate"],
    ["bin.duplicate", "Duplicate a bin", "moderate"],
    ["bin.delete", "Delete a bin", "destructive"],
    ["bin.move", "Move a bin within the project", "moderate"],
    ["bin.createFolder", "Create a project/bin folder", "low"],
    ["bin.setView", "Apply a bin view", "low"],
    ["bin.setColumns", "Show, hide, and reorder bin columns", "low"],
    ["bin.sort", "Sort bin contents", "low"],
    ["bin.sift", "Apply a bin sift/filter", "low"],
    ["bin.selectItems", "Select named or identified bin items", "low"],
    ["bin.moveItems", "Move items between bins", "moderate"],
    ["bin.duplicateItems", "Duplicate clips or sequences into a bin", "moderate"],
    ["bin.deleteItems", "Delete selected bin items", "destructive"],
  ],
  media: [
    ["media.link", "Link media through UME/AMA", "moderate"],
    ["media.import", "Import media into managed Avid storage", "external"],
    ["media.batchImport", "Batch import or reimport media", "external"],
    ["media.transcode", "Transcode selected media", "external"],
    ["media.consolidate", "Consolidate selected media", "external"],
    ["media.relink", "Relink clips or sequences", "destructive"],
    ["media.unlink", "Unlink selected clips", "destructive"],
    ["media.refresh", "Refresh linked media", "low"],
    ["media.setSourceSettings", "Change source interpretation settings", "moderate"],
    ["media.modifyClip", "Modify clip metadata or interpretation", "moderate"],
    ["media.createSubclip", "Create a subclip from source marks", "moderate"],
    ["media.syncAuto", "Create synchronized clips using selected criteria", "moderate"],
    ["media.group", "Create a group clip", "moderate"],
    ["media.multigroup", "Create a multigroup clip", "moderate"],
  ],
  source: [
    ["source.load", "Load a clip or sequence into the Source monitor", "low"],
    ["source.clear", "Clear the Source monitor", "low"],
    ["source.markIn", "Set source IN", "low"],
    ["source.markOut", "Set source OUT", "low"],
    ["source.clearMarks", "Clear source marks", "low"],
    ["source.setPosition", "Set source monitor position", "low"],
    ["source.matchFrame", "Match frame from record to source", "low"],
    ["source.findBin", "Reveal the loaded source in its bin", "low"],
    ["source.toggleGang", "Gang or ungang source and record monitors", "low"],
  ],
  sequence: [
    ["sequence.create", "Create a sequence", "moderate"],
    ["sequence.createFromClips", "Create a sequence from selected clips", "moderate"],
    ["sequence.load", "Load a sequence into the Record monitor", "low"],
    ["sequence.duplicate", "Duplicate a sequence", "moderate"],
    ["sequence.rename", "Rename a sequence", "moderate"],
    ["sequence.delete", "Delete a sequence", "destructive"],
    ["sequence.setStartTimecode", "Change sequence start timecode", "moderate"],
    ["sequence.setFormat", "Change sequence format", "destructive"],
    ["sequence.commitMulticam", "Commit a multicam edit", "destructive"],
    ["sequence.decompose", "Decompose a sequence", "moderate"],
  ],
  timeline: [
    ["timeline.spliceIn", "Splice source material into the timeline", "moderate"],
    ["timeline.overwrite", "Overwrite timeline material", "destructive"],
    ["timeline.replaceEdit", "Replace a timeline segment with source material", "destructive"],
    ["timeline.lift", "Lift marked timeline material", "destructive"],
    ["timeline.extract", "Extract marked timeline material and close the gap", "destructive"],
    ["timeline.clear", "Clear selected timeline material", "destructive"],
    ["timeline.addEdit", "Add edits on selected tracks", "moderate"],
    ["timeline.rippleDelete", "Delete a segment and ripple later material", "destructive"],
    ["timeline.segmentMove", "Move selected timeline segments", "destructive"],
    ["timeline.segmentOverwrite", "Move segments in overwrite mode", "destructive"],
    ["timeline.segmentLift", "Lift selected segments", "destructive"],
    ["timeline.trim", "Perform a trim edit", "destructive"],
    ["timeline.rippleTrim", "Perform a single-roller ripple trim", "destructive"],
    ["timeline.rollTrim", "Perform a dual-roller roll trim", "destructive"],
    ["timeline.slip", "Slip source content inside a segment", "destructive"],
    ["timeline.slide", "Slide a segment while trimming its neighbors", "destructive"],
    ["timeline.extend", "Extend an edit to the playhead", "destructive"],
    ["timeline.fitToFill", "Perform a fit-to-fill edit", "destructive"],
    ["timeline.nest", "Nest selected effects or segments", "moderate"],
    ["timeline.duplicateSegment", "Duplicate a timeline segment", "moderate"],
    ["timeline.restoreMatchFrame", "Restore a matching source frame", "moderate"],
    ["timeline.setSyncLocks", "Set timeline sync-lock state", "low"],
  ],
  track: [
    ["track.createVideo", "Create a video track", "moderate"],
    ["track.createAudio", "Create an audio track", "moderate"],
    ["track.createData", "Create a data track", "moderate"],
    ["track.delete", "Delete a track", "destructive"],
    ["track.rename", "Rename a track", "low"],
    ["track.reorder", "Reorder tracks", "destructive"],
    ["track.patchSource", "Patch source tracks to record tracks", "low"],
    ["track.target", "Target or untarget record tracks", "low"],
    ["track.monitor", "Set monitored video/audio tracks", "low"],
    ["track.lock", "Lock or unlock tracks", "low"],
    ["track.mute", "Mute or unmute audio tracks", "low"],
    ["track.solo", "Solo or unsolo audio tracks", "low"],
  ],
  effect: [
    ["effect.apply", "Apply an effect", "moderate"],
    ["effect.remove", "Remove an effect", "destructive"],
    ["effect.replace", "Replace an effect", "destructive"],
    ["effect.setParameter", "Set an effect parameter", "moderate"],
    ["effect.addKeyframe", "Add an effect keyframe", "moderate"],
    ["effect.updateKeyframe", "Update an effect keyframe", "moderate"],
    ["effect.deleteKeyframe", "Delete an effect keyframe", "destructive"],
    ["effect.applyTransition", "Apply a transition", "moderate"],
    ["effect.removeTransition", "Remove a transition", "destructive"],
    ["effect.promote", "Promote an effect to advanced controls", "moderate"],
    ["effect.render", "Render selected effects", "external"],
    ["effect.unrender", "Delete rendered effect media", "destructive"],
    ["effect.collapse", "Collapse selected tracks or layers", "moderate"],
  ],
  audio: [
    ["audio.setClipGain", "Set clip gain", "moderate"],
    ["audio.setPan", "Set clip or track pan", "moderate"],
    ["audio.setTrackGain", "Set track gain", "moderate"],
    ["audio.addAutomationKeyframe", "Add an audio automation keyframe", "moderate"],
    ["audio.updateAutomationKeyframe", "Update audio automation", "moderate"],
    ["audio.deleteAutomationKeyframe", "Delete audio automation", "destructive"],
    ["audio.applyAudioSuite", "Apply an AudioSuite process", "external"],
    ["audio.normalize", "Normalize selected audio", "external"],
    ["audio.mixdown", "Create an audio mixdown", "external"],
    ["audio.setPhase", "Set audio phase inversion", "moderate"],
    ["audio.setChannelMapping", "Set source audio channel mapping", "destructive"],
  ],
  color: [
    ["color.applyCorrection", "Apply color correction", "moderate"],
    ["color.setCorrection", "Set color-correction parameters", "moderate"],
    ["color.copyCorrection", "Copy a color correction", "low"],
    ["color.pasteCorrection", "Paste a color correction", "moderate"],
    ["color.applyLut", "Apply a source or timeline LUT", "moderate"],
    ["color.removeLut", "Remove a LUT", "destructive"],
    ["color.render", "Render color corrections", "external"],
  ],
  marker: [
    ["marker.addSource", "Add a source marker", "low"],
    ["marker.addRecord", "Add a sequence marker", "low"],
    ["marker.update", "Update marker text, color, or metadata", "low"],
    ["marker.delete", "Delete a marker", "destructive"],
    ["marker.import", "Import markers", "moderate"],
    ["marker.export", "Export markers", "external"],
  ],
  titleCaption: [
    ["title.create", "Create a title", "moderate"],
    ["title.edit", "Edit title text and style", "moderate"],
    ["title.applyTemplate", "Apply a title template", "moderate"],
    ["caption.createTrack", "Create a caption track", "moderate"],
    ["caption.import", "Import captions or subtitles", "moderate"],
    ["caption.edit", "Edit caption text and timing", "moderate"],
    ["caption.delete", "Delete captions or a caption track", "destructive"],
  ],
  multicam: [
    ["multicam.createGroup", "Create a grouped multicam clip", "moderate"],
    ["multicam.setBank", "Set the active multicam bank", "low"],
    ["multicam.switchAngle", "Switch the active multicam angle", "destructive"],
    ["multicam.audioFollowVideo", "Set audio-follows-video behavior", "moderate"],
    ["multicam.commit", "Commit multicam edits", "destructive"],
  ],
  playback: [
    ["playback.play", "Start playback", "low"],
    ["playback.stop", "Stop playback", "low"],
    ["playback.shuttle", "Set shuttle speed and direction", "low"],
    ["playback.step", "Step by frames or fields", "low"],
    ["playback.goto", "Move the position indicator", "low"],
    ["playback.loop", "Toggle loop playback", "low"],
    ["playback.setInOut", "Set record monitor IN and OUT", "low"],
    ["playback.clearInOut", "Clear record monitor marks", "low"],
  ],
  output: [
    ["output.exportFile", "Export a sequence or clip to a file", "external"],
    ["output.exportAaf", "Export AAF", "external"],
    ["output.exportAle", "Export ALE", "external"],
    ["output.exportEdl", "Export EDL or list output", "external"],
    ["output.exportFrame", "Export a still frame", "external"],
    ["output.mixdownVideo", "Create a video mixdown", "external"],
    ["output.mixdownAudio", "Create an audio mixdown", "external"],
    ["output.sendToPlayback", "Send media to a configured playback system", "external"],
    ["output.queue", "Queue an output job", "external"],
    ["output.cancel", "Cancel an output job", "destructive"],
  ],
  workspace: [
    ["workspace.activate", "Activate a workspace", "low"],
    ["workspace.save", "Save a workspace", "moderate"],
    ["workspace.setPanel", "Open, close, dock, or focus a panel", "low"],
    ["settings.updateUser", "Update a user setting", "moderate"],
    ["settings.updateProject", "Update a project setting", "moderate"],
    ["settings.updateSite", "Update a site setting", "destructive"],
    ["keyboard.invokeCommand", "Invoke a named, mapped Media Composer command", "moderate"],
  ],
};

export const EDIT_ACTION_CATALOG: EditActionDefinition[] = Object.entries(CATEGORY_SEEDS)
  .flatMap(([category, seeds]) =>
    seeds.map(([action, description, risk = "moderate", verification]) => ({
      action,
      category,
      description,
      risk,
      destructive: risk === "destructive",
      verification:
        verification ??
        `Re-inspect ${category} state and confirm the intended change after '${action}'.`,
      adapter: "media-composer-extension" as const,
    })),
  )
  .sort((a, b) => a.action.localeCompare(b.action));

export const EDIT_ACTIONS = new Map(
  EDIT_ACTION_CATALOG.map((definition) => [definition.action, definition]),
);
