import {mkdir,writeFile,readFile} from 'node:fs/promises';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
import {runProcess} from '../../dist/process.js';
import {loadConfig} from '../../dist/config.js';
import {MediaLibrary} from '../../dist/library/media-library.js';
import {MediaQc} from '../../dist/library/qc.js';
import {sha256File} from '../../dist/analysis/file-inventory.js';
const root=path.resolve('.avid-mcp-analysis',`qc-${randomUUID()}`);await mkdir(root);
const file=path.join(root,'known-black-silence.mp4');
const generated=await runProcess('ffmpeg',['-hide_banner','-nostdin','-v','error','-n','-f','lavfi','-i','color=black:s=160x90:r=30:d=2','-f','lavfi','-i','testsrc2=s=160x90:r=30:d=4','-f','lavfi','-i','anullsrc=r=48000:cl=mono:d=2','-f','lavfi','-i','sine=frequency=1000:sample_rate=48000:duration=4','-filter_complex','[0:v][1:v]concat=n=2:v=1:a=0[v];[2:a][3:a]concat=n=2:v=0:a=1[a]','-map','[v]','-map','[a]','-c:v','libx264','-pix_fmt','yuv420p','-c:a','aac',file],{timeoutMs:30000,maxOutputBytes:1048576});assert.equal(generated.exitCode,0,generated.stderr);
const config=loadConfig({AVID_MCP_ALLOWED_ROOTS:root,AVID_MCP_OUTPUT_ROOT:root,AVID_MCP_CAPABILITIES:'inspect,export'}),library=new MediaLibrary(config),qc=new MediaQc(config);
const indexed=await library.index([file]),id=indexed.entries[0].id;
const report=await qc.analyze(id,{start:1,end:5,freezeSeconds:0.5});
const near=(value,target)=>assert.ok(Math.abs(value-target)<0.08,`${value} differs from ${target}`);
near(report.findings.black[0].start,1);near(report.findings.black[0].end,2);
near(report.findings.freeze[0].start,1);near(report.findings.freeze[0].end,2);
near(report.findings.silence[0].start,1);near(report.findings.silence[0].end,2);
assert.ok(Number.isFinite(report.findings.loudness.integratedLufs));assert.equal(await sha256File(file),id);
assert.match(await readFile(report.html,'utf8'),/Media QC report/);
const sonomaConfig=loadConfig({AVID_MCP_ALLOWED_ROOTS:'D:/Sonoma Escape Edit',AVID_MCP_OUTPUT_ROOT:'.avid-mcp-analysis/sonoma-library-20260905',AVID_MCP_CAPABILITIES:'inspect,export'});
const sonomaId='3025fb298baee4c3beec50480a3d9376c99d0fc79d05f55f91e2e1c500539fca';
const sonoma=await new MediaQc(sonomaConfig).analyze(sonomaId,{start:60,end:90});
assert.equal(await sha256File('D:/Sonoma Escape Edit/Sonoma_Escape_RoughCut_v1_preview.mp4'),sonomaId);
await writeFile(path.join(root,'evidence.json'),JSON.stringify({fixture:report,sonoma,sourceUnchanged:true},null,2));
console.log(JSON.stringify({passed:true,fixtureIntervalToleranceSeconds:0.08,sonomaRange:[60,90],evidence:path.join(root,'evidence.json')}));
