import {People} from '../../dist/library/people.js';
import {loadConfig} from '../../dist/config.js';
import {writeFile,access} from 'node:fs/promises';
import {sha256File} from '../../dist/analysis/file-inventory.js';
import assert from 'node:assert/strict';
const config=loadConfig({AVID_MCP_ALLOWED_ROOTS:'D:/Sonoma Escape Edit',AVID_MCP_OUTPUT_ROOT:'.avid-mcp-analysis/sonoma-library-20260905',AVID_MCP_MODEL_DIR:'.avid-mcp-analysis/models',AVID_MCP_CAPABILITIES:'inspect,export,project-write'});
const people=new People(config),id='3025fb298baee4c3beec50480a3d9376c99d0fc79d05f55f91e2e1c500539fca';
const index=await people.index([id],12);assert.ok(index.faces>=2);
const clusters=await people.list(index.indexId),faces=await people.faces(index.indexId,undefined);assert.ok(clusters.clusters.length>=2);
const operations=[];let revision=index.revision;
const edit=async operation=>{const result=await people.edit(index.indexId,revision,operation);revision=result.revision;operations.push({operation,result});return result;};
await edit({action:'name',clusterId:clusters.clusters[0].clusterId,name:'Qualification group'});
await edit({action:'merge',from:clusters.clusters[1].clusterId,into:clusters.clusters[0].clusterId});
await edit({action:'move',faceId:faces.faces[1].faceId,into:null});
await edit({action:'recluster',threshold:0.45});
await edit({action:'remove_face',faceId:faces.faces[0].faceId});
await assert.rejects(access(faces.faces[0].crop));
const removed=await people.remove(index.indexId,revision);assert.equal(removed.sourceMediaDeleted,false);
assert.equal(await sha256File('D:/Sonoma Escape Edit/Sonoma_Escape_RoughCut_v1_preview.mp4'),id);
await writeFile('.avid-mcp-analysis/sonoma-library-20260905/people-operations.json',JSON.stringify({index,operations,removed,sourceUnchanged:true},null,2));
console.log(JSON.stringify({passed:true,faces:index.faces,operations:operations.length,indexDeleted:true,sourceUnchanged:true}));
