import {mkdir,rename,writeFile,readFile} from 'node:fs/promises';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
import {loadConfig} from '../../dist/config.js';
import {WatchFolders} from '../../dist/library/watch-folders.js';
import {MediaLibrary} from '../../dist/library/media-library.js';
import {runProcess} from '../../dist/process.js';
const output=path.resolve('.avid-mcp-analysis',`watch-${randomUUID()}`),folder=path.join(output,'watched');
await mkdir(folder,{recursive:true});
const file=path.join(folder,'fixture.mp4');
const generated=await runProcess('ffmpeg',['-nostdin','-v','error','-n','-f','lavfi','-i','testsrc2=size=160x90:rate=30','-t','1','-c:v','libx264',file],{timeoutMs:30000,maxOutputBytes:1048576});
assert.equal(generated.exitCode,0);
const config=loadConfig({AVID_MCP_ALLOWED_ROOTS:folder,AVID_MCP_OUTPUT_ROOT:output,AVID_MCP_CAPABILITIES:'inspect,project-write,export'});
const service=new WatchFolders(config),watch=await service.configure({folder});
const first=await service.scan(watch.id),second=await service.scan(watch.id);
assert.equal(first.indexed.length,0);assert.equal(second.indexed.length,1);
const id=second.indexed[0].id;
const library=new MediaLibrary(config),transcript=await library.importTranscript(id,[{start:0,end:1,text:'Synthetic fixture'}]);
assert.equal((await new WatchFolders(config).scan(watch.id)).indexed.length,0);
const moved=path.join(folder,'moved.mp4');await rename(file,moved);
await service.scan(watch.id);const relocated=await service.scan(watch.id);
assert.equal(relocated.indexed[0].id,id);
assert.equal((await library.metadata([id]))[0].file,moved);
assert.equal((await library.transcriptRange(id,0,1,-1,10,transcript.revision)).segments[0].text,'Synthetic fixture');
service.start(10);assert.equal(service.stop().running,false);
await service.remove(watch.id);assert.equal((await readFile(moved)).length>0,true);
const evidence={passed:true,first,second,relocated,transcript};await writeFile(path.join(output,'evidence.json'),JSON.stringify(evidence,null,2));
console.log(JSON.stringify({passed:true,output,id,checks:['stability','real-probe','checkpoint-restart','moved-source','transcript-retained','stop','remove-keeps-media']}));
